---
- name: Install xbfb
  apt:
    name: xvfb
    state: present

- name: Install firefox
  apt:
    name: firefox
    state: present

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Install virtualenv for python3
  pip:
    name: virtualenv
    executable: pip3
